### ISSUE TITLE
Quaternion skinning problem

### ISSUE THREAD

**Issue by ForserX** [xrOxygen/xray-oxygen#257]
All bones has visible anyway. 
![15-11-2018 00-56-56](https://user-images.githubusercontent.com/13867290/48515623-423cd980-e872-11e8-8870-f76bc27c4582.png)
https://github.com/xrOxygen/xray-oxygen/commit/0f624b50b561648344217e7a806531dd2bf153e1

**Comment by MatthewKush** [comment]
The C++ part is confusing so I can't help there, but I've been working on this a bit anyway. Quaternions are some tricky shit indeed but I'll do my best.

I suggest we do what other engines do though: instead of putting it in a header like it currently is we could make it into a Compute shader so it runs real fast.

We also don't have to stick to GSC's style of doing it: we can "borrow" from somewhere with simpler code and shaders for skinning.

If you'd rather I just fix what's there I can do that instead, but that file has always been messy. I'd suggest replacing it. Just my two cents.

**Comment by ForserX** [comment]
Branch removed. Bye-bye
