### ISSUE TITLE
sky and textures

### ISSUE THREAD

**Issue by S3r1ous** [xrOxygen/xray-oxygen#96]
it seems the weather isnt changing/clouds arent moving also some textures are uhh too shiny?
https://s14.postimg.org/m3oc7d7kh/ss_user1_04-04-18_16-34-43_zaton.png
log (looks ok): https://justpaste.it/1j6qh

**Comment by ForserX** [comment]
@S3r1ous, hmmm...

**Comment by Swartz27** [comment]
I know what the problem is: this was clearly designed for r2_gloss_factor to be set to 1. You also need to go into ps_combine_1.hlsl, find the line "float3 spec = C.www * L.rgb + hspecular" and change it to vanilla, which is "float3 spec = C.www + hspecular"

Not only should this solve any issues, I must say that the lighting looks really nice.

**Comment by S3r1ous** [comment]
hmm rocks are fine now but
https://s14.postimg.org/wnz6stk9d/ss_user1_04-05-18_20-27-39_zaton.png

**Comment by ForserX** [comment]
Delete user.ltx
